name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          clean: true

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish WPF
        run: dotnet publish src/TwitchMemeAlertsAuto.WPF/TwitchMemeAlertsAuto.WPF.csproj --configuration Release --runtime win-x64 --self-contained false /p:PublishDir=.\publish-wpf\ /p:PublishSingleFile=false /p:PublishReadyToRun=true

      - name: Create WPF ZIP archive
        run: |
          $version = "${{ github.ref_name }}"
          $zipName = "tmaa-wpf.zip"
          $publishPath = Join-Path $PWD 'src\TwitchMemeAlertsAuto.WPF\publish-wpf\'
          Compress-Archive -Path (Join-Path $publishPath '*') -DestinationPath $zipName -Force
          Write-Host "Created $zipName from $publishPath"
          echo "WPF_ZIP=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Publish CLI
        run: dotnet publish src/TwitchMemeAlertsAuto.CLI/TwitchMemeAlertsAuto.CLI.csproj --configuration Release --runtime win-x64 --self-contained true /p:PublishDir=.\publish-cli\ /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Publish AutoUpdater.xml
        run: |
          echo "<?xml version=""1.0"" encoding=""UTF-8""?>
          <item>
          <version>$env:GitVersion_AssemblySemVer</version>
          <url>https://github.com/NowaLone/TwitchMemeAlertsAuto/releases/latest/download/tmaa-wpf.zip</url>
          <changelog>https://github.com/NowaLone/TwitchMemeAlertsAuto/releases</changelog>
          <mandatory>false</mandatory>
          </item>" | Out-File -FilePath src\TwitchMemeAlertsAuto.WPF\publish-wpf\AutoUpdater.xml


      - name: Upload assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.WPF_ZIP }}
            src/TwitchMemeAlertsAuto.CLI/publish-cli/tmaa.exe
            src/TwitchMemeAlertsAuto.WPF/publish-wpf/AutoUpdater.xml
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}